server:
  port: 8082
spring:
  application:
    name: 'client-demo-application'
  security:
    user:
      name: "client"
      password: "client"
  boot:
    admin:
      client:
        url: 'http://localhost:8081'
        username: "admin"
        password: "admin"
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
