server:
  port: 8082
spring:
  application:
    admin:
      name: 'client-demo-application'
  boot:
    admin:
      client:
        url: 'http://localhost:8081'
        username: 'admin'
        password: 'admin'

management:
  endpoints:
    web:
      exposure:
        include: '*'
